# Generated by Django 3.0.1 on 2020-01-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_1', models.CharField(max_length=100)),
                ('heading_2', models.CharField(max_length=100)),
                ('bg_image', models.ImageField(upload_to='sliderimages')),
            ],
        ),
    ]
